### ISSUE TITLE
Finished

### ISSUE THREAD

**Issue by LeaChemoul** [PolytechLyon/2019-isi3-graph-berger-chemoul#8]
TP isi3 graph finished

**Comment by Slashgear** [comment]
- [ ] Les UML ne sont pas visible sur github (souci de path)
- [ ] Le `@NotNull`sort d'où ? C'est disponible avec Java Directement ? Expliquer moi ce qu'il fait ? Justifiez moi son usage 
- [ ] Pourquoi utiliser des variables préfixées de `_`, comment le justifiez vous ?

Dans l'ensemble c'est très bien 👍 

- 💡 (non obligatoire) Si vous êtes curieux la programmation fonctionnelle peut vous aider à simplifier vos fonction `toString`

**Comment by Slashgear** [comment]
⚠️ Pas touche à mes commentaires merci !

**Comment by Slashgear** [comment]
Prévenez moi quand vous avez pris tous les retours

**Comment by LeaChemoul** [comment]
Nous avons fini vos retours.
Pour ce qui est de la partie @NotNull, elle est expliquée dans le rapport (ligne 71).

**Comment by Slashgear** [comment]
Ces annotations n'ont aucun impact sur la compilation et sur l'execution. c'est pour moi du bruit inutile. Elle ne vous protège pas du tout que cette variable devienne null à un moment.

Un variable doit être non null par défaut.
Si elle est nullable, il faudrait se servir de Optional<T> en Java 

Sinon c'est bien, tp terminé

**Comment by Cynnexis** [comment]
Les annotations `@NotNull` et `@Nullable` proviennent d'une librairie créée par IntelliJ. Elles servent à aider l'IDE à vérifier que le code semble correcte (en soulignant une variable où l'on affecte `null` alors qu'elle fut annotée avec `@NotNull`), mais elles ont aussi une utilité lors de l'exécution. Java 8 contient une fonctionnalité appelée "**Annotation Processor**", qui permet d'associer une annotation à une fonction (par l'intermédiaire d'une classe). Dépendemment du déclencheur choisit, la fonction va être appelé lors du Runtime.

Dans le cas de `@NotNull`, la librairie fournit également une fonction associée à cette annotation : A chaque fois que la variable (ou paramètre) est modifiée, la fonction est executée, et si la nouvelle valeur est `null`, un `NullPointerException` est levée. Cela nous permet d'optimiser notre code pour 2 raisons : La première est que nous pouvons remplacer les setters de type :

```java
public void setValue(Object value) {
    if (value == null)
        throw new NullPointerException();
    
    this.value = value;
}
```

directement par :

```java
public void setValue(@NotNull Object value) {
    this.value = value;
}
```

et aussi d'autre part à pouvoir vérifier facilement que tous nos attributs sont non-null, ce qui nous permet de nous passer des `assert value != null;`.

Source :
* [JetBrains Documention](https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html)
* [Baeldung - Java Annotation Processing](https://www.baeldung.com/java-annotation-processing-builder)

**Comment by Slashgear** [comment]
Je comprends tout à fait, mais une des façon d'éviter les NullPointerException en Java est de jamais affecter null à un objet 😄 

Si cependant l'objet peut ne pas être défini, l'Optional est le moyen "vanilla" (sans framwork/librairie/IDE) qui vous en protègera :)
